language: haskell

sudo: false


notifications:
  email: false

cache:
  directories:
    - $HOME/.stack/

before_install:
 before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin
  - chmod a+x ~/.local/bin/stack

install:
 - stack setup --no-terminal
 - stack build --only-snapshot --no-terminal

script:
 - stack --no-terminal --test